"""Mini-Project 1: Step-by-step cooking assistant (masala tea)."""
print("How to make one cup of masala tea")
print("----------------------------------")
print("Step 1: Pour 150 ml of water and 100 ml of milk into a small saucepan.")
print("Step 2: Add 1 teaspoon of tea leaves, 2 crushed cardamom pods and a thin slice of ginger.")
print("Step 3: Put the saucepan on the stove and turn the burner to medium.")
print("Step 4: Check whether the tea is boiling. If not, keep heating and check again after 30 seconds.")
print("Step 5: When it boils, turn the burner to low and let it simmer for 2 minutes.")
print("Step 6: Add 1 teaspoon of sugar and stir for 10 seconds.")
print("Step 7: Turn off the burner.")
print("Step 8: Pour the tea through a strainer into a cup. Serve hot.")
